<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="text-center mb-5">
                <h1 class="display-5 fw-bold text-primary">
                    <i class="fa-duotone fa-book-sparkles me-2"></i>Decryption Protocols
                </h1>
                <p class="lead text-body-secondary">
                    Standard Operating Procedures for Signal Analysis
                </p>
            </div>

            <div class="card shadow-sm mb-4 border-0 bg-body-tertiary">
                <div class="card-body p-4">
                    <h4 class="card-title fw-bold mb-3">
                        <i class="fa-duotone fa-crosshairs me-2 text-danger"></i>Mission Objective
                    </h4>
                    <p class="card-text">
                        A rogue signal has been detected. Your goal is to decrypt the <strong>Secret Code</strong> generated by the system. You must deduce the exact sequence of digits through trial, error, and logic.
                    </p>
                </div>
            </div>

            <div class="card shadow-sm mb-4 border-0 bg-body-tertiary">
                <div class="card-body p-4">
                    <h4 class="card-title fw-bold mb-3">
                        <i class="fa-duotone fa-wave-pulse me-2 text-info"></i>Signal Parameters
                    </h4>
                    <ul class="list-group list-group-flush bg-transparent">
                        <li class="list-group-item bg-transparent d-flex align-items-start border-0 px-0">
                            <i class="fa-duotone fa-check-circle text-success mt-1 me-3"></i>
                            <div>
                                <strong>Four Digits:</strong> The code is exactly 4 numbers long.
                            </div>
                        </li>
                        <li class="list-group-item bg-transparent d-flex align-items-start border-0 px-0">
                            <i class="fa-duotone fa-check-circle text-success mt-1 me-3"></i>
                            <div>
                                <strong>Range 1-5:</strong> Each digit is between 1 and 5.
                            </div>
                        </li>
                        <li class="list-group-item bg-transparent d-flex align-items-start border-0 px-0">
                            <i class="fa-duotone fa-check-circle text-success mt-1 me-3"></i>
                            <div>
                                <strong>Unique Signals:</strong> No digit is repeated. (e.g., <code>1234</code> is valid; <code>1123</code> is impossible).
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="card shadow-sm mb-4 border-primary">
                <div class="card-header bg-primary text-white">
                    <i class="fa-duotone fa-magnifying-glass-chart me-2"></i>Reading the Feedback
                </div>
                <div class="card-body p-4 bg-body-tertiary">
                    
                    <div class="alert alert-warning d-flex align-items-center mb-4" role="alert">
                        <i class="fa-duotone fa-sort-amount-down fa-2x me-3"></i>
                        <div>
                            <strong>Priority Sorting:</strong> The Stardust Engine always displays <strong>(+)</strong> symbols first.
                            <br>
                            <small>The position of a symbol in the result does <em>not</em> correspond to the position of the digit in your guess.</small>
                        </div>
                    </div>

                    <p>After every guess, the system returns a set of symbols:</p>
                    
                    <div class="d-flex align-items-center mb-4 p-3 bg-body border rounded">
                        <div class="display-6 fw-bold text-success me-4 ps-2">+</div>
                        <div>
                            <h5 class="fw-bold text-success mb-1">Signal Locked (Plus)</h5>
                            <p class="mb-0 small text-body-secondary">You have a correct number in the <strong>correct</strong> spot.</p>
                        </div>
                    </div>

                    <div class="d-flex align-items-center mb-3 p-3 bg-body border rounded">
                        <div class="display-6 fw-bold text-warning me-4 ps-3">-</div>
                        <div>
                            <h5 class="fw-bold text-warning mb-1">Signal Detected (Minus)</h5>
                            <p class="mb-0 small text-body-secondary">You have a correct number, but it is in the <strong>wrong</strong> spot.</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="d-grid gap-2">
                <a href="/apps/cipher" class="btn btn-outline-primary btn-lg">
                    <i class="fa-duotone fa-arrow-left me-2"></i>Return to Decryptor
                </a>
            </div>

        </div>
    </div>
</div>